

export const packages_data = {
    Logo: [


        {
            id: 1,
            title: "Beginner Website",
            price: "199",
            was: "796",
            package: [
                "1 Page Website",
                "1 jQuery Slider Banner",
                "Contact/Query Form",
                "Complete W3C Certified HTML",
                "48 to 72 hours TAT",
                "Complete Deployment",
                "100% Satisfaction Guarantee",
                "100% Unique Design Guarantee",
                "100% Money Back Guarantee *",

            ],
        },

        {
            id: 2,
            title: "Startup Website",
            price: "475",
            was: "1900",
            package: [
                "5 Page Website",
                "3 Banner Design",
                "1 jQuery Slider Banner",
                "FREE Google Friendly Sitemap",
                "Complete W3C Certified HTML",
                "48 to 72 hours TAT",
                "100% Satisfaction Guarantee",
                "100% Unique Design Guarantee",
                "100% Money Back Guarantee *",
                "Mobile Responsive will be Additional $200*",
                "CMS will be Additional $250*",
            ],
        },

        {
            id: 3,
            title: "Professional Website",
            price: "650",
            was: "2600",
            package: [
                "10 Unique Pages Website",
                "CMS / Admin Panel Support",
                "8 Stock images",
                "5 Banner Designs",
                "1 jQuery Slider Banner",
                "FREE Google Friendly Sitemap",
                "Complete W3C Certified HTML",
                "48 to 72 hours TAT",
                "Complete Deployment",
                "100% Satisfaction Guarantee",
                "100% Unique Design Guarantee",
                "100% Money Back Guarantee *",
                "Mobile Responsive will be Additional $200*",
            ],
        },

        {
            id: 4,
            title: "Corprate Website",
            price: "2499",
            was: "9996",
            package: [
                "15 to 20 Pages Website",
                "Custom Made, Interactive, Dynamic & High End Design",
                "Custom WP (or) Custom PHP Development",
                "1 jQuery Slider Banner",
                "Up to 10 Custom Made Banner Designs",
                "10 Stock Images",
                "Unlimited Revisions",
                "Special Hoover Effects",
                "Content Management System (CMS)",
                "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
                "Online Payment Integration (Optional)",
                "Multi Lingual (Optional)",
                "Custom Dynamic Forms (Optional)",
                "Signup Area (For Newsletters, Offers etc.)",
                "Search Bar",
                "Live Feeds of Social Networks integration (Optional)",
                "Mobile Responsive",
                "Free Google Friendly Sitemap",
                "Search Engine Submission",
                "Complete W3C Certified HTML",
                "Industry Specified Team of Expert Designers and Developers",
                "Complete Deployment",
                "Dedicated Accounts Manager",
                "100% Ownership Rights",
                "100% Satisfaction Guarantee",
                "100% Unique Design Guarantee",
                "100% Money Back Guarantee *",
            ],
        },

        {
            id: 5,
            title: "Business Website",
            price: "2699",
            was: "10796",
            package: [
                "15 Seconds 2D Explainer Video",
                "Voice - Over & Sound Effects",
                "Professional Script Writing",
                "Storyboard",
                "SEO Meta Tags",
                "15 to 20 Pages Website",
                "Custom Made, Interactive, Dynamic & High End Design",
                "Custom WP (or) Custom PHP Development",
                "1 jQuery Slider Banner",
                "Up to 10 Custom Made Banner Designs",
                "10 Stock Images",
                "Unlimited Revisions",
                "Special Hoover Effects",
                "Content Management System (CMS)",
                "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
                "Online Payment Integration (Optional)",
                "Multi Lingual (Optional)",
                "Custom Dynamic Forms (Optional)",
                "Signup Area (For Newsletters, Offers etc.)",
                "Search Bar",
                "Live Feeds of Social Networks integration (Optional)",
                "Mobile Responsive",
                "Free Google Friendly Sitemap",
                "Search Engine Submission",
                "Complete W3C Certified HTML",
                "Industry Specified Team of Expert Designers and Developers",
                "Complete Deployment",
                "Dedicated Accounts Manager",
                "100% Ownership Rights",
                "100% Satisfaction Guarantee",
                "100% Unique Design Guarantee",
                "100% Money Back Guarantee *",
            ],
        },

    ],

    Ecommerce: [
        {
            id: 1,
            title: "E-Commerce Professional",
            price: "750",
            was: "3000",
            package: [
                "E-Commerce Website Design and Development",
                "Customized Theme Based Design",
                "7 Banner Designs",
                "Sliding Banner",
                "7 Stock Photos",
                "Unlimited Revisions",
                "Hover Effects",
                "Up to 100 Products",
                "Up to 10 Categories",
                "Content/Inventory Management System",
                "Mobile Responsive",
                "Easy Product Search Bar",
                "Shopping Cart Integration",
                "Payment Module Integration",
                "Direct Checkout",
                "Sign up Checkout",
                "Wishlist",
                "Social Media Pages Integration",
                "Sitemap",
                "Complete W3C Validation",
                "Dedicated Team of Designers and Developers",
                "Complete Deployment",
                "– Value Added Services -",
                "Complete Source Files",
                "Dedicated Project Manager",
                "100% Ownership Rights",
                "100% Satisfaction Guarantee",
                "100% Money Back Guarantee",
                "NO MONTHLY OR ANY HIDDEN FEE",
            ],
        },

        {
            id: 2,
            title: "E-Commerce Elite",
            price: "1230",
            was: "4920",
            package: [
                "E-Commerce Website Design and Development",
                "Customized Tailor-Made Design",
                "Professional, Modern, Unique Design",
                "10 Banner Designs",
                "Sliding Banner",
                "10 Stock Photos",
                "Unlimited Revisions",
                "Special Hover Effects",
                "Up to 500 Products",
                "Up to 25 Categories",
                "Product Reviews & Ratings",
                "Content/Inventory Management System",
                "Mobile Responsive",
                "Easy Product Search Bar",
                "Shopping Cart Integration",
                "Payment Module Integration",
                "Direct Checkout",
                "Sign up Checkout",
                "Wishlist",
                "Social Media Pages Integration",
                "Blog page (If Required)",
                "Sitemap",
                "Complete W3C Validation",
                "Complete Deployment",
                "– Value Added Services -",
                "Complete Source Files",
                "Dedicated Project Manager",
                "100% Ownership Rights",
                "100% Satisfaction Guarantee",
                "100% Money Back Guarantee",
                "NO MONTHLY OR ANY HIDDEN FEE",
            ],
        },

        {
            id: 3,
            title: "E-Commerce Identity",
            price: "1650",
            was: "6600",
            package: [

                "E-Commerce Website Design and Development",
                "Customized Tailor-Made Design",
                "Professional, Modern, Interactive, Dynamic, Unique Design",
                "User-friendly Navigation",
                "15 Banner Designs",
                "Sliding Banner",
                "15 Stock Photos",
                "48 to 72 hours TAT",
                "Unlimited Revisions",
                "Special Hover Effects",
                "Content/Inventory Management System",
                "Mobile Responsive",
                "1000 Products",
                "Unlimited Categories",
                "Product Reviews & Ratings",
                "Product Summary Reports (Out of stock / Most Sold / Lowest sale etc) By Date",
                "Product Detail with Similar Product Range",
                "Product Comparison",
                "Discounted Products Showcase",
                "New Arrival Products Showcase",
                "Discount Coupons",
                "Easy Product Search Bar",
                "Shopping Cart Integration",
                "Payment Module Integration",
                "Direct Checkout",
                "Sign up Checkout",
                "Wishlist",
                "Bulk Product Upload From Excel Sheet",
                "Export order into excel sheet",
                "Social Media Pages Integration",
                "Blog page (If Required)",
                "Sitemap",
                "Complete W3C Validation",
                "Dedicated Team of Designers and Developers",
                "Complete Deployment",
                "– Value Added Services -",
                "Complete Source Files",
                "Dedicated Project Manager",
                "100% Ownership Rights",
                "100% Satisfaction Guarantee",
                "100% Money Back Guarantee",
                "NO MONTHLY OR ANY HIDDEN FEE",
            ],
        },

        {
            id: 4,
            title: "E-Commerce Corprate ",
            price: "3650",
            was: "14600",
            package: [
                "E-Commerce Website Design and Development",
                "Customized Tailor-Made Design",
                "Professional, Modern, Interactive, Dynamic, Unique Design",
                "User-friendly Navigation",
                "20 Banner Designs",
                "Sliding Banner",
                "20 Stock Photos",
                "Unlimited Revisions",
                "Special Hover Effects",
                "Content/Inventory Management System",
                "Mobile Responsive",
                "Unlimited Products",
                "Unlimited Categories",
                "Product Reviews & Ratings",
                "Product Summary Reports (Out of stock / Most Sold / Lowest sale etc) By Date",
                "Product Rating",
                "Product Detail with Similar Product Range",
                "Product Comparison",
                "Discounted Products Showcase",
                "New Arrival Products Showcase",
                "Discount Coupons",
                "Easy Product Search Bar",
                "Payment Module Integration",
                "Direct Checkout",
                "Sign up Checkout",
                "Wishlist",
                "Bulk Product Upload From Excel Sheet",
                "Export order into excel sheet",
                "Social Media Pages Integration",
                "Facebook Shop Setup",
                "Blog page (If Required)",
                "Sitemap",
                "Complete W3C Validation",
                "Dedicated Team of Designers and Developers",
                "Complete Deployment",
                "– Value Added Services -",
                "Complete Source Files",
                "Dedicated Project Manager",
                "100% Ownership Rights",
                "100% Satisfaction Guarantee",
                "100% Money Back Guarantee",
                "NO MONTHLY OR ANY HIDDEN FEE",
            ],
        },



    ],
}

export const web_work = [
    {
        title: 'Landing Pages', description: 'Attract and convert potential customers with high-converting landing pages designed for specific campaigns or products',
        image: 'https://res.cloudinary.com/dmwykcrki/image/upload/v1748283069/landing-page-design-and-development-services_vshnar.png'
    },
    {
        title: 'Business Website', description: 'Showcase your brand with user friendly website that reflects your businesses values and goals',
        image: 'https://res.cloudinary.com/dmwykcrki/image/upload/v1748283071/website-design-preview-119635_d7jph0.jpg'
    },
    {
        title: 'E-commerce Website', description: 'Create an online store that provides a smooth shopping experience, secure transactions, and drives conversions.',
        image: 'https://res.cloudinary.com/dmwykcrki/image/upload/v1748283065/016029115483405.604f9358065f1_tfbkir.png'
    },
    {
        title: 'Blogs & Content Website', description: 'Build a content-rich website that engages visitors, ranks well on search engines, and keeps your audience coming back.',
        image: 'https://res.cloudinary.com/dmwykcrki/image/upload/v1748283065/banner_ohm3is.webp'
    },

    {
        title: 'Custom Website Application', description: 'Tailored web apps that meet the unique needs of your business, ensuring smooth functionality and scalability.',
        image: 'https://res.cloudinary.com/dmwykcrki/image/upload/v1748283064/84abf4184403667.6551a930b3b2b_lxbr7g.jpg'
    },
]

export const testimonals = [
    {
        review: 'What stood out the most was not only their deep understanding of our industry but also their ability to leverage that knowledge with a data-driven approach. They were able to analyze key trends, identify actionable insights, and apply data to make informed decisions that truly resonated with our business needs. It was clear that they had a comprehensive grasp of both the big picture and the finer details, which made all the difference in crafting tailored strategies for our success.',
        nameOf: 'George brook ',
        position: 'Direct of Board, Brush Buck Tours',
        image: 'https://res.cloudinary.com/dmwykcrki/image/upload/v1748285290/vvccv_txidi9.png',

    },
    {
        review: 'Their strong collaboration played a key role in making the entire process so easy. By working seamlessly together, they ensured everything moved forward without delays, milestone based tasks were delivered timely and efficiently.This smooth coordination not only sped up the process but also contributed to the overall success of the project',
        nameOf: 'Elli Noyon',
        position: 'Recruiter',
        image: 'https://res.cloudinary.com/dmwykcrki/image/upload/v1748283282/hq720_u6fvew.png',

    },
    {
        review: 'The SEO strategies that Texas Design Experts implemented were customized to fit the unique needs of our industry. Focusing on our sector’s specific requirements, they helped us achieve significant, measurable results. This approach led to increased website orders organically , increased website traffic, and better engagement, all of which were clear indicators of the strategy\'s success.',
        nameOf: 'Jessica Born',
        position: 'Project Manager',
        image: 'https://res.cloudinary.com/dmwykcrki/image/upload/v1748284982/dddddd_bvmq0d.png',

    }
]

export const our_work_data = [
    {category : "All" , images : [
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365384/mjfsez9g69mgfvzpjhtd.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365380/evvixafk5uxh3mswenmu.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365379/erryy0icgxi5csu2cvei.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365379/vqzl4mgvv3vbuffeqzsz.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365377/ekvvyj8nsptbi9tedpop.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365377/heulngkjcvew0yvxw0wo.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365374/ue5pbkstgyyxhsbuafw7.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365368/dg8ife7k2vmwltperr7f.webp'
        
    ]},

    {category : "Auto" , images : [
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365429/fwfoaod1mx9f5wx8hffh.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365430/ixzituy9hqtw2nptlem1.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365428/pchcmtx2kucqiod2fitw.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365427/ebdezdg3prr5envhy8zl.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365427/lvciqrlutreaiu2klhef.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365426/gmwndtlyvsiqeupvrtvy.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365426/s3ljcflckojbdirsh8m4.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365424/tvzqine8llbhsfslrqes.webp'
    ]},

    {category : "Business" , images : [
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365896/fzgcrpgn0ldfe1fkssee.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365896/o3rpmbcv0ulwle4tuiqv.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365896/pbk6mkpmwewl6m8qt3ax.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365893/rkqvthz4rbk8la2sgh7y.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365891/ttnfc3sktereqxshp3va.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365891/vktyivcla0ovlmax0weg.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365891/a3ykgl62hr3shghgngrp.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365889/ph6syccbie8tra1j5izl.webp',
    ]},

    {category : "Custom" , images : [
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365936/vwg4fz5y4ybh5haz9e6x.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365933/woz0y5on0cliw0tzlqqh.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365931/xmzdkucfyxsyoxj6woee.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365931/jj2klzcjn3bihhz1eno6.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365928/how9oqyfvrodjmfulcax.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365926/pjyoj5dx8vfl8vunumwf.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365924/uxhgsoaal69kaguithuq.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365923/n1nqkhagcirqwcdymext.webp'
    ]},

    {category : "Food" , images : [
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365975/e156ms795h4cc9ul8ngw.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365973/kvyil9hilrttjg6oy6ep.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365970/m4vvtxg9p2nufrmzqg5q.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365970/cnmgw3u9aeahvvx70rdn.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365968/hng2o1gpyhw3lmgkrkpt.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365965/fhquob6lphjjyi7i2fnn.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365965/be11iyuwvriayjjyjmgc.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748365962/d1go0vgxlhvwzahsogva.webp'

    ]},

    {category : "E-commerce Store" , images : [
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366031/wkd351v6fqog7dx3ycmp.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366028/xbigveeyjrxjgzf5scts.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366026/azhwjamhbxavwazdqhnp.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366024/jtep7qxjb9v9pegz7gx5.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366021/tbodwhz0cj4ps6qdmw4b.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366018/ngundioxugf8xskzuxhv.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366016/cummlai0snwzismsrjaq.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366015/l1nmnsjsu4bocp5t5uta.webp'
    ]},

    {category : "Personal" , images : [
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366131/pyyqchqxwvyvikdwtibe.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366128/nwszvdfudqcprtgo5or3.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366117/bmrcd9uaqeelmomdbjlm.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366114/sydlaebtorir3uhvxykw.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366110/ncoxgji2x5a6iscytf0n.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366107/ksflxaieg2sag0iqgdpv.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366105/vilhbbteqmhxa0jd1q7h.webp',
        'https://res.cloudinary.com/dwbt0uoa7/image/upload/v1748366103/js4zxeksqgw0enfoy14o.webp'
    ]},

    
]
