

export const packages_data = {
    Logo : [


    {id : 1 ,
        title : "Beginner Website",
        price : "199",
        was : "796",
        package : [
            "4 Unique Logo Concepts" ,
            "FREE Icon",
            "Unlimited Revisions" ,
            "AI, PSD, EPS, GIF, BMP, JPEG PNG Formats",
            "Free Rush Delivery" ,
            "Get Initial Concepts within 24 hours",
        ],   
    },

    {id : 2 ,
        title : "Startup Website",
        price : "475",
        was : "1900",
        package : [
            "4 Unique Logo Concepts" ,
            "FREE Icon",
            "Unlimited Revisions" ,
            "AI, PSD, EPS, GIF, BMP, JPEG PNG Formats",
            "Free Rush Delivery" ,
            "Get Initial Concepts within 24 hours",
        ],   
    },

    {id : 3 ,
        title : "Professional Website",
        price : "650",
        was : "2600",
        package : [
            "4 Unique Logo Concepts" ,
            "FREE Icon",
            "Unlimited Revisions" ,
            "AI, PSD, EPS, GIF, BMP, JPEG PNG Formats",
            "Free Rush Delivery" ,
            "Get Initial Concepts within 24 hours",
        ],   
    },

    {id : 4 ,
        title : "Corprate Website",
        price : "2499",
        was : "9996",
        package : [
            "4 Unique Logo Concepts" ,
            "FREE Icon",
            "Unlimited Revisions" ,
            "AI, PSD, EPS, GIF, BMP, JPEG PNG Formats",
            "Free Rush Delivery" ,
            "Get Initial Concepts within 24 hours",
        ],   
    },

    {id : 5 ,
        title : "Business Website",
        price : "2699",
        was : "10796",
        package : [
            "4 Unique Logo Concepts" ,
            "FREE Icon",
            "Unlimited Revisions" ,
            "AI, PSD, EPS, GIF, BMP, JPEG PNG Formats",
            "Free Rush Delivery" ,
            "Get Initial Concepts within 24 hours",
        ],   
    },
    
    ],

    Ecommerce : [
        {id : 1 ,
            title : "Beginner Website",
            price : "199",
            was : "796",
            package : [
                "4 Unique Logo Concepts" ,
                "FREE Icon",
                "Unlimited Revisions" ,
                "AI, PSD, EPS, GIF, BMP, JPEG PNG Formats",
                "Free Rush Delivery" ,
                "Get Initial Concepts within 24 hours",
            ],   
        },
    
        {id : 2 ,
            title : "Startup Website",
            price : "475",
            was : "1900",
            package : [
                "4 Unique Logo Concepts" ,
                "FREE Icon",
                "Unlimited Revisions" ,
                "AI, PSD, EPS, GIF, BMP, JPEG PNG Formats",
                "Free Rush Delivery" ,
                "Get Initial Concepts within 24 hours",
            ],   
        },
    
        {id : 3 ,
            title : "Professional Website",
            price : "650",
            was : "2600",
            package : [
                "4 Unique Logo Concepts" ,
                "FREE Icon",
                "Unlimited Revisions" ,
                "AI, PSD, EPS, GIF, BMP, JPEG PNG Formats",
                "Free Rush Delivery" ,
                "Get Initial Concepts within 24 hours",
            ],   
        },
    
        {id : 4 ,
            title : "Corprate Website",
            price : "2499",
            was : "9996",
            package : [
                "4 Unique Logo Concepts" ,
                "FREE Icon",
                "Unlimited Revisions" ,
                "AI, PSD, EPS, GIF, BMP, JPEG PNG Formats",
                "Free Rush Delivery" ,
                "Get Initial Concepts within 24 hours",
            ],   
        },
    
        {id : 5 ,
            title : "Business Website",
            price : "2699",
            was : "10796",
            package : [
                "4 Unique Logo Concepts" ,
                "FREE Icon",
                "Unlimited Revisions" ,
                "AI, PSD, EPS, GIF, BMP, JPEG PNG Formats",
                "Free Rush Delivery" ,
                "Get Initial Concepts within 24 hours",
            ],   
        },
        
    ],
}